package com.yuntongxun.plugin.greendao3.bean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.List;
import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {


    private static NNDaoSession nDaoSession;
    private ISession iSession;

    public void initDaoAndEntityClass() {

        if (iSession != null) {
            List<Class> entityClass = iSession.getEntityClass();
            List<AbstractDao> sessionDao = iSession.getSessionDao();
            int abc = 0;
            for (Class obj : entityClass) {
                registerDao(obj, sessionDao.get(abc));
                abc++;
            }
        }
    }

    public DaoSession(Database db) {
        super(db);
    }

    public void initSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        if (nDaoSession != null) {
            nDaoSession.setNDaoSession(db, type, daoConfigMap, this);
        }
    }

    public void clear() {
        if (nDaoSession != null) {
            nDaoSession.setNClear();
        }
    }

    public static void setDaoSessionListener(NNDaoSession znDaoSession) {
        nDaoSession = znDaoSession;
    }

    public interface NNDaoSession {
        void setNDaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
                daoConfigMap, DaoSession ad);

        void setNClear();
    }


    public void setRegisterDaoListener(ISession session) {
        iSession = session;
    }

}
